# Generated by Django 4.2.4 on 2023-08-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0002_userdashboarddatabase'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDataBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=50)),
                ('contact', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
